### ISSUE TITLE
I'm going to kill myself on this container ... not literally ... lack of sleep

### ISSUE THREAD

**Issue by jasonhollis** [HomeSeerLinux/homeseer-docker#1]
Boss,

I get:

: invalid option
: invalid option

No matter how I try to deploy this container. That's the return.  I will be happy to pay you $500 for a 1 hr zoom.  I've owned pro for many years and ran in a container before for a long time.  I know I'm missing something.  I've studied the compose files but I have not sorted it out yet.  I have slept 3.5 hrs a night for 3 days.

I have not gone wide in my distribution choices but I get the same thing everywhere.  I've not automated the buster build.

I setup 3 ISP's in Austin before I was 21, worked at Dell and many other places.  I'm not slow.  I'm missing something.  I'm an old man now but bent on working this out.  It does have commercial applications for me.

Your help would be most appreciated sir.  

Kind regards,

Jason

**Comment by jasonhollis** [comment]
I don't know how to effectively debug in this environment.  If you could help me with that it would be most useful.

**Comment by savageautomate** [comment]
Are you still interested in getting this working?  If so, I'll try to figure out whats failing.

**Comment by savageautomate** [comment]
I was able to easily reproduce the problem.  It appears that the line endings in the bash startup script files were not encoded properly for unix/linux.  I have fixed the issue and re-deployed updated docker images.  I'm not exactly sure how this happened as I only work on Linux and MacOS machines but probably something to do with how git attempts to auto manage line endings on files.

You should stop and remove any existing `homeseer` containers and remove the old images before trying the new images.

```
docker stop homeseer
docker rm homeseer
docker image rm homeseer/homeseer
```

Please re-open this issue if you have any trouble with it.  
Thanks, Robert

**Comment by jasonhollis** [comment]
Robert,

Thanks for the update.  I will check it out.

Best regards,

Jason
