### ISSUE TITLE
Cannot install Plugins

### ISSUE THREAD

**Issue by JJWatMyself** [HomeSeerLinux/homeseer-docker#2]
Hi there.  I am coming from 4.1.10.0 on Synology (Docker) to 4.2.17.0 on Proxmox LXC (Docker). I am using MACVLAN so the container gets a dedicated IP (same as before), but having issues with adding Plugins... Not sure if it is related to this or a different issue.  Error is:

![image](https://user-images.githubusercontent.com/22590445/227743018-86494801-7aa1-4668-9176-c16e4aef4a41.png)

**Comment by JJWatMyself** [comment]
This issue was addressed as discovered the firewall was blocking downloads.  homeseer.com file downloads is required for file types .dll .zip .exe

![image](https://user-images.githubusercontent.com/22590445/230733841-6b9ed8d5-dd28-489b-864e-6c541e5ba80f.png)

**Comment by JJWatMyself** [comment]
See above post.

**Comment by savageautomate** [comment]
@JJWatMyself 

Thanks for posting these details and the resolution.  I was scratching my head trying to think of why downloads would get blocked ..... but glad to hear it was just a firewall issue.      Thanks, Robert
