### ISSUE TITLE
Preserving setup between updates

### ISSUE THREAD

**Issue by ocgltd** [HomeSeerLinux/homeseer-docker#3]
Could you confirm if all config data (events/zwave/setup/plugin data/etc) are kept in the host directory?  If not could you explain how to preserve these during backups?

**Comment by savageautomate** [comment]
Config, data files, logs, etc are all maintained and preserved.

The "volume" argument in the Docker command or Docker compose is used to define a volume/directory on your host system that is mapped into the Docker container.  This directory is the entire Homeseer installation and data directory.  On first start of the container, the homeseer linux application is installed into this directory and potentially overwrites any existing program files but only program files included in the homeseer linux distribution archive.  Other files such as log files, config files and plugs are not touched.
```
-v /etc/homeseer:/homeseer 
```

Thanks, Robert
